Repository hack4impact-utk/internal-applications, pull requests merged in 2024-04, with the labels that each got.

#156 72 create bargraphanalytics component
  apps/form-builder/package.json
  apps/form-builder/src/app/page.tsx
  apps/form-builder/src/components/FormSubmissions/BarGraphAnalytics/Index.tsx
  package-lock.json
  package.json
Labels: Member Portal

#158 32 create form page
  apps/admin-portal/package.json
  apps/applicant-tracking/package.json
  apps/form-builder/package.json
  apps/form-builder/src/app/api/forms/[formId]/formQuestions/[formQuestionId]/route.ts
  apps/form-builder/src/app/forms/[formId]/page.tsx
  apps/form-builder/src/components/FormTabs/index.tsx
  apps/member-portal/package.json
  package-lock.json
  package.json
Labels: Member Portal

#196 Created component
  apps/form-builder/src/app/forms/[formId]/page.tsx
  apps/form-builder/src/components/FormSettings/index.tsx
Labels: Member Portal

#172 CreateFormRequest Component with useState
  apps/form-builder/src/app/page.tsx
  apps/form-builder/src/components/NewFormQuestion/NewFormQuestion.tsx
  package-lock.json
Labels: Member Portal

#210 140 create numericoptions component
  apps/form-builder/src/components/NumericOptions.tsx
Labels: Member Portal

#213 131 create new form button
  apps/form-builder/src/app/forms/page.tsx
  package-lock.json
Labels: Member Portal

#212 59 create multiplechoicequestionanalytics component
  apps/form-builder/src/app/api/forms/[formId]/formquestions/[formQuestionId]/route.ts
  apps/form-builder/src/app/page.tsx
  apps/form-builder/src/components/MultipleChoiceQuestionAnalytics/Index.tsx
Labels: Member Portal

#206 Added getAllMembers function
  packages/internal-models/src/db/actions/Members.ts
Labels: Admin Portal, ap-server

#204 Re-styled member component with card design
  apps/admin-portal/src/components/Member/index.tsx
Labels: Admin Portal, ap-components
